services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb

  searching_service_redis:
    image: redis:latest

  search_service:
    build:
      context: ./search_service
    ports:
      - "8001:8000"
    depends_on:
      - db
      - searching_service_redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://youruser:yourpassword@db/yourdb
      - REDIS_URL=redis://searching_service_redis:6379
    volumes:
      - ./search_service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  booking_service_redis:
    image: redis:latest

  rabbitmq:
    image: "rabbitmq:3-management"

  booking_producer_service:
    build:
      context: ./booking_producer_service
    ports:
      - "8002:8000"
    depends_on:
      - booking_service_redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://booking_service_redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_PORT=5672
      - BOOKING_CONSUMER_URL=http://booking_consumer_service:8000/booking_consuming
    volumes:
      - ./booking_producer_service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  
  booking_consumer_service:
    build:
      context: ./booking_consumer_service
    environment:
      - DATABASE_URL=postgresql+asyncpg://youruser:yourpassword@db/yourdb
      - REDIS_URL=redis://booking_service_redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8003:8000"
    depends_on:
      - db
      - booking_service_redis
      - rabbitmq
    volumes:
      - ./booking_consumer_service:/app


  confirming_service_redis:
    image: redis:latest


  confirming_service:
    build: 
      context: ./confirming_service
    environment:
      - DATABASE_URL=postgresql+asyncpg://youruser:yourpassword@db/yourdb
      - REDIS_URL=redis://confirming_service_redis:6379
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./confirming_service:/app
    ports:
      - "8004:8000"
    depends_on:
      - db
      - confirming_service_redis