version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_db_cache:
    image: redis:latest
    ports:
      - "6380:6379"

  search_service:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis_db_cache
    environment:
      - DATABASE_URL=postgresql+asyncpg://youruser:yourpassword@db/yourdb
      - REDIS_URL=redis://redis_db_cache:6379
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
