version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: flights
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  web:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/flights
      - REDIS_URL=redis://redis:6379

volumes:
  db_data:
