services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5433:5432"

  
  confirming_service_redis:
    image: redis:latest
    ports:
      - "6380:6379"

  confirming_service:
    build: .
    environment:
      - DATABASE_URL=postgresql+asyncpg://youruser:yourpassword@db/yourdb
      - REDIS_URL=redis://confirming_service_redis:6379
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
      - confirming_service_redis

