services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5433:5432"



  booking_service_redis:
    image: redis:latest
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  booking_consumer_service:
    build: .
    environment:
      - DATABASE_URL=postgresql+asyncpg://youruser:yourpassword@db/yourdb
      - REDIS_URL=redis://booking_service_redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    depends_on:
      - db
      - booking_service_redis
      - rabbitmq
    volumes:
      - .:/app

