version: '3.8'

services:
  booking_service_redis:
    image: redis:latest
    ports:
      - "6380:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5673:5672"
      - "15673:15672"

  booking_producer_service:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - booking_service_redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://booking_service_redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_PORT=5672
      - BOOKING_CONSUMER_URL=http://booking_consumer_service:8000/
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

