version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5673:5672"
      - "15673:15672"

  booking_producer_service:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - BOOKING_CONSUMER_URL=http://booking_consumer_service:8000/
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

